deals/urls.py
from django.urls import path

from .views import Home, TaskAddSuccess, TaskDetail, TaskList

app_name = 'deals'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('task/', TaskList.as_view(), name='task_list'),
    path('task/<slug:slug>/', TaskDetail.as_view(), name='task_detail'),
    path('added/', TaskAddSuccess.as_view(), name='task_added'),
]

static_pages/urls.py
from django.urls import path

from .views import About

app_name = 'static_pages'

urlpatterns = [
    path('about/', About.as_view(), name='about'),
]

todo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('deals.urls', namespace='deals')),
    path('page/', include('static_pages.urls', namespace='static_pages')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

deals/models.py
from django.db import models
# pip3 install pytils не забыть установить!
from pytils.translit import slugify


class Task(models.Model):
    title = models.CharField(
        'Заголовок',
        default='Значение по-умолчанию',
        max_length=100,
        help_text='Дайте короткое название задаче'
    )
    text = models.TextField(
        'Текст',
        help_text='Опишите суть задачи'
    )
    slug = models.SlugField(
        'Адрес для страницы с задачей',
        max_length=100,
        unique=True,
        blank=True,
        help_text=('Укажите адрес для страницы задачи. Используйте только '
                   'латиницу, цифры, дефисы и знаки подчёркивания')
    )
    image = models.ImageField(
        'Картинка',
        upload_to='tasks/',
        blank=True,
        null=True,
        help_text='Загрузите картинку'
    )

    def __str__(self):
        return self.title

    # Расширение встроенного метода save(): если поле slug не заполнено -
    # транслитерировать в латиницу содержимое поля title и
    # обрезать до ста знаков
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)[:100]
        super().save(*args, **kwargs)

deals/forms.py
from django import forms
from django.core.exceptions import ValidationError
from pytils.translit import slugify

from .models import Task


class TaskCreateForm(forms.ModelForm):
    """Форма для создания задания."""
    class Meta:
        model = Task
        # Магия Джанго: через '__all__' создаётся форма из всех полей модели
        # labels и help_texts берутся из verbose_name и help_text
        fields = '__all__'

    # Валидация поля slug
    def clean_slug(self):
        """Обрабатывает случай, если slug не уникален."""
        cleaned_data = super().clean()
        slug = cleaned_data['slug']
        if not slug:
            title = cleaned_data['title']
            slug = slugify(title)[:100]
        if Task.objects.filter(slug=slug).exists():
            raise ValidationError(f'Адрес "{slug}" уже существует, '
                                  'придумайте уникальное значение')
        return slug

deals/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import CreateView

from .forms import TaskCreateForm
from .models import Task


class Home(CreateView):
    """Форма добавления задания."""
    template_name = 'deals/home.html'
    form_class = TaskCreateForm
    success_url = reverse_lazy('deals:task_added')


class TaskList(LoginRequiredMixin, ListView):
    """Список всех доступных заданий."""
    login_url = '/admin/login/'
    model = Task
    template_name = 'deals/task_list.html'



class TaskDetail(LoginRequiredMixin, DetailView):
    """Задание подробно."""
    login_url = '/admin/login/'
    model = Task
    template_name = 'deals/task_detail.html'


class TaskAddSuccess(TemplateView):
    """Задание успешно добавлено."""
    template_name = 'deals/added.html'

static_pages/views.py
from django.views.generic.base import TemplateView


class About(TemplateView):
    template_name = 'static_pages/about.html'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>
    <title>TODO</title>
</head>
<body>
    {% block navbar %}{% endblock navbar %}
    {% block content %}{% endblock content %}
</body>
</html>

templates/deals/added.html
{% extends 'base.html' %}
{% load static %}
{% block navbar %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">TODO</a>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link " href="{% url 'deals:home' %}">Домашняя страница</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'static_pages:about' %}">О проекте</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'deals:task_list' %}">Cписок задач</a>
          </li>
        </ul>s
      </div>
    </div>
  </nav>
{% endblock navbar %}
{% block content %}

  <div class="container py-5">
    <h1>Задача успешно добавлена</h1>
    <a href="{% url 'deals:home' %}">На главную</a>
  </div>
{% endblock content %}

templates/deals/home.html
{% extends 'base.html' %}
{% load static %}
{% block navbar %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">TODO</a>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'deals:home' %}">Домашняя страница</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'static_pages:about' %}">О проекте</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'deals:task_list' %}">Cписок задач</a>
          </li>
        </ul>s
      </div>
    </div>
  </nav>
{% endblock navbar %}
{% block content %}

  <div class="container py-5">
    <h2>Добавить задачу</h2>
    <!-- enctype определяет способ кодирования данных формы
    при их отправке на сервер.
    Обычно устанавливать значение атрибута enctype не требуется,
    данные вполне правильно понимаются на стороне сервера.
    Однако если используется поле для отправки файла (input type="file"),
    следует определить атрибут enctype как multipart/form-data. -->
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}
      <div class="form-group row my-3 p-3">
        {{ field.label }}
        {{ field }}
        {{ field.help_text }}
      </div>
      {% endfor %}
      <input type="submit" value="Сохранить">
    </form>
  </div>
{% endblock content %}

templates/deals/task_detail.html
<html>
  <body>
    <h1>Детализация задачи ID: {{ task.id }}</h1>
    <ul>
      <li>
        <a href="{% url 'deals:home' %}">На главную</a>
      </li>
      <li>
        <a href="{% url 'deals:task_list' %}">В список задач</a>
      </li>
    </ul>
    <h2>{{ task.title }}</h2>
    <p>{{ task.text }}</p>
    {% if task.image %}
      <img src="{{ task.image.url }}">
    {% endif %}

  </body>
</html>

templates/deals/task_list.html
{% extends 'base.html' %}
{% load static %}
{% block navbar %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">TODO</a>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link " href="{% url 'deals:home' %}">Домашняя страница</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'static_pages:about' %}">О проекте</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'deals:task_list' %}">Cписок задач</a>
          </li>
        </ul>s
      </div>
    </div>
  </nav>
{% endblock navbar %}
{% block content %}

  <div class="container py-5">
    <ul>
      {% for task in object_list %}
        <li>
          <a href="{% url 'deals:task_detail' task.slug %}">{{ task.title }}</a>
        </li>
      {% endfor %}
    </ul>
    <a href="{% url 'deals:home' %}">На главную</a>
  </div>
{% endblock content %}

templates/static_pages/about.html
{% extends 'base.html' %}
{% load static %}
{% block navbar %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">TODO</a>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link " href="{% url 'deals:home' %}">Домашняя страница</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'static_pages:about' %}">О проекте</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'deals:task_list' %}">Cписок задач</a>
          </li>
        </ul>s
      </div>
    </div>
  </nav>
{% endblock navbar %}
{% block content %}

  <div class="container py-5">
    <p>
      Проект Todo поможет вам не забыть о самом важном
    </p>
    <a href="{% url 'deals:home' %}">На главную</a>
  </div>
{% endblock content %}